### ISSUE TITLE
release by maven

### ISSUE THREAD

**Issue by thomaswoehlke** [Computer-Kurzweil/cyclic-cellular-automaton#3]
- [ ] #10 update to java 17
- [ ] #9 setup maven project reports site
- [ ] #4 change buttons to checkbuttons
- [ ] #3 release by maven
